import Link from "next/link";
import { redirect } from "next/navigation";
import { isAuthed } from "@/lib/admin-auth";
import { getAllSeminars, formatPrice } from "@/lib/seminars-db";
import { deleteSeminarAction } from "@/app/admin/actions";
import AdminShell from "@/components/admin/AdminShell";

export const dynamic = "force-dynamic";
export const metadata = { title: "Админка — семинары", robots: { index: false, follow: false } };
export default function SeminarsPage({ searchParams }: { searchParams: { created?: string; updated?: string; deleted?: string } }) { if (!isAuthed()) redirect("/admin/login"); const seminars = getAllSeminars(); const notice = searchParams.created ? "Семинар создан." : searchParams.updated ? "Изменения сохранены." : searchParams.deleted ? "Семинар удалён." : null; return <AdminShell active="/admin/seminars"><div className="flex items-center justify-between gap-4 mb-6"><div><h2 className="font-cormorant text-3xl text-[var(--ink)]">Семинары</h2><p className="font-inter text-sm text-[var(--ink-soft)]">Расписание отображается на публичной странице.</p></div><Link href="/admin/seminars/new" className="btn-gold rounded-full px-5 py-2.5 font-inter text-xs uppercase tracking-widest">Новый семинар</Link></div>{notice && <p className="mb-5 rounded-xl bg-[var(--sage)]/10 px-4 py-3 font-inter text-sm text-[var(--sage)]">{notice}</p>}<div className="space-y-3">{seminars.map((seminar) => <article key={seminar.id} className="flex flex-col gap-4 rounded-2xl border border-[var(--line)] bg-white/60 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-inter text-xs uppercase tracking-widest text-[var(--gold)]">{seminar.format} · {seminar.dateStart} — {seminar.dateEnd}</p><h3 className="font-cormorant text-xl text-[var(--ink)] mt-1">{seminar.title}</h3><p className="font-inter text-sm text-[var(--ink-soft)] mt-1">{seminar.location} · {formatPrice(seminar.price)}</p></div><div className="flex gap-3"><Link className="rounded-full border border-[var(--line)] px-4 py-2 font-inter text-xs uppercase tracking-widest text-[var(--ink-soft)] hover:border-[var(--gold)]" href={`/admin/seminars/${seminar.id}`}>Редактировать</Link><form action={deleteSeminarAction}><input type="hidden" name="id" value={seminar.id} /><button className="rounded-full border border-[var(--rose-color)]/40 px-4 py-2 font-inter text-xs uppercase tracking-widest text-[var(--rose-color)] hover:bg-[var(--rose-color)]/10">Удалить</button></form></div></article>)}</div></AdminShell>; }
